# Customize this file, documentation can be found here:
# https://docs.fastlane.tools/actions/
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.68.1"

default_platform :ios

platform :ios do
  before_all do
    carthage
  end

  desc "Runs all the tests"
  lane :test do
    run_tests
  end

  lane :screenshots do
    capture_screenshots
    frame_screenshots(white: true)
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    increment_build_number
    build_app(scheme: "HackerNews")
    screenshots
    upload_to_testflight
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    screenshots
    build_app(scheme: "HackerNews")
    upload_to_app_store(force: true)
  end

end
